import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PokemonCharacters from "./characters";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://pokeapi.co">Pokemons!</a>
        </h1>

        <div className={styles.main_scroll_view}>
          <PokemonCharacters />
        </div>
      </main>
    </div>
  );
};

export default Home;
